### ISSUE TITLE
Problem installing the vdemdata package

### ISSUE THREAD

**Issue by fpmassam** [vdeminstitute/vdemdata#34]
When I try to install the package I get this error: 

```
Error: Failed to install 'vdemdata' from GitHub:
  (converted from warning) cannot remove prior installation of package ‘testthat’
```

`R version 4.0.3 (2020-10-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19041)
`

**Comment by vdeminstitute** [comment]
Thanks, try again now, the package 'testthat' is not really needed and was erased from the 'suggest' list so should be working now. In any case, you might like to manually remove the 'testthat' package on your machine since it seems to be an outdated version.

**Comment by fpmassam** [comment]
Thanks so much! Say hello to everyone up there (proud former intern speaking here)

**Comment by vdeminstitute** [comment]
:-) best wishes!
