### ISSUE TITLE
dataset version 

### ISSUE THREAD

**Issue by timothoms** [vdeminstitute/vdemdata#35]
While an API (as, for instance, for UCDP) would be even more useful, it's great that VDem is making this R package available. I have 2 suggestions: 

- VDem announced a dataset update (11.1) by email today, and the website recommends this package for R users. But the package has no indication of which dataset version is included (it seems that it is version 11.0). There needs to be either a function to easily check the version, or an indicator in the dataframes themselves to identify the version.  

- Currently, the package has no help files. At least minimal documentation is needed to accompany the functions included in the package. 

Thanks!

**Comment by vdeminstitute** [comment]
Thanks for your feedback, we have now also updated the vdemdata package with v11.1, the package specifies which version is used. With ?function you can access our detailed documentation for each function in the package.
