### ISSUE TITLE
Information on Deprecated Variables

### ISSUE THREAD

**Issue by DvP17** [vdeminstitute/vdemdata#37]
Thank you very much for this package!

I would like to ask if it would be possible to also include information on deprecated variables in the `find_var()` function?

I was looking for an old variable called "e_Fiscal_Reliance" from version 8. Unfortunately, it is not included in VDEM anymore and I have not found information in the codebook of v9 and v10 that it is not longer included. Thus, it might be a good idea to provide some information on old variables that are not part of VDEM anymore and information if, e.g., notation of certain variables has changed. This might help to troubleshoot when using old code.

Kind regards

**Comment by SeraphineM** [comment]
Hi, thanks for using our package and your feedback! 

The vdemdata R package loads vdem dataset versions starting with v10. You find information on old variables and other changes in the codebooks for each version of the dataset, available in the archive here: https://www.v-dem.net/en/data/data/v-dem-dataset-v111/ (click Data/Archive). 

I hope this helps and best wishes,
Seraphine

**Comment by DvP17** [comment]
Dear Seraphine,

I cannot see any information on old variables on the website. I know that the vdem function sources the last available dataset. I was asking for a way to make change in variables more transparent. 

Instead of closing this issue it might be helpful to think about this as a possible future enhancement.

All the best.

**Comment by SeraphineM** [comment]
Hi, yes, this could be a future enhancement - in the meantime you'll find information on old variables in the codebooks (not on the website) which are available in the archive here:  https://www.v-dem.net/en/data/data/v-dem-dataset-v111/ (click Data/Archive).
