### ISSUE TITLE
Inconcruence with version available on website

### ISSUE THREAD

**Issue by danweitzel** [vdeminstitute/vdemdata#40]
Hey y'all, 

I've come across a small issue. Calling the data set using the vdem function loads a version of the data that has missing values for the v2x_polyarchy variable for Mozambique between the years 1974 and 1993. If I download the V-Dem-CY-Full+Others-v12 file from the website I do get v2x_polyarchy observations for Mozambique during this time. 

Additionally, the Github page speaks of the V-Dem data set but the website lists four different versions of the data set. Since the data set called through the package includes 4176 variables I am assuming that it is the V-Dem-CY-Full+Others-v12 file. It might be helpful if the package would reference the data set and version that it provides. 

Thanks for providing this package!

**Comment by abedgell** [comment]
Thanks for the inquiry. Are you sure you have updated to the latest version of the package? You can do so using the following commands within R: 

`install.packages("devtools")`
`devtools::install_github("vdeminstitute/vdemdata")`

After re-installing the latest version of the package, you can use the following command to verify that Mozambique has the full time series from v12: 

`vdemdata::plot_indicator(indicator = "v2x_polyarchy", countries = "Mozambique")`

**Comment by danweitzel** [comment]
I hang my head in shame. 
Yeah, this was the issue. Thanks for the quick response and help!

**Comment by abedgell** [comment]
No problem! I've also updated the README to include more specificity on the version of the V-Dem dataset and some suggested citations. Thanks for that tip.
