### ISSUE TITLE
package not available for 

### ISSUE THREAD

**Issue by mcw215** [vdeminstitute/vdemdata#44]
When installing the package [install.packages("vdemdata")] for R 4.2.1, the warning message says: "package ‘vdemdata’ is not available for this version of R"

**Comment by SeraphineM** [comment]
I assume this is because your system does not automatically install all dependencies (in this case: rtools, dplyr, tidyr, stringr, ggplot2, tidyselect) if packages are loaded from git. Try to install all dependencies manually, restart R, and check again. If the problem persists, please let me know.
